# Use this docker-compose file to setup the test environment before running the
# tests.

services:
  couchbase:
    image: couchbase/server:7.6.1
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    volumes:
      - couchbase_data:/opt/couchbase/var

  nsqlookupd:
    platform: linux/amd64
    image: nsqio/nsq:v1.3.0
    command: >
      /nsqlookupd --log-level=error
    hostname: nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161

  nsqd:
    platform: linux/amd64
    image: nsqio/nsq:v1.3.0
    command: >
      /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=${EXTERNAL_IP} --max-msg-size=1413820683
      --log-level=error
    environment:
      - "EXTERNAL_IP=${EXTERNAL_IP}"
    hostname: nsqd
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151

  nsqadmin:
    platform: linux/amd64
    image: nsqio/nsq:v1.3.0
    command: >
      /nsqadmin --lookupd-http-address=nsqlookupd:4161 --log-level=error
    hostname: nsqadmin
    depends_on:
      - nsqlookupd
    ports:
      - 4171:4171

  minio:
    platform: linux/amd64
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"

  ui:
    platform: linux/amd64
    image: saferwall/ui:latest
    ports:
      - "3000:3000"
    environment:
      PUBLIC_API_URL: http://localhost:8080/v1/
      PUBLIC_AVATAR_API_URL: https://avatar.saferwall.com/{username}

  orchestrator:
    platform: linux/amd64
    image: saferwall/orchestrator:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/orchestrator-svc, -config, /saferwall/conf/]
    volumes:
      - /samples:/samples

  aggregator:
    platform: linux/amd64
    image: saferwall/aggregator:latest
    depends_on:
      - couchbase
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/aggregator-svc, -config, /saferwall/conf/]
    restart: always

  postprocessor:
    platform: linux/amd64
    image: saferwall/postprocessor:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/postprocessor-svc, -config, /saferwall/conf/]
    volumes:
      - /samples:/samples
    restart: always

  pe:
    platform: linux/amd64
    image: saferwall/pe:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/pe-svc, -config, /saferwall/conf/]
    volumes:
      - /samples:/samples

  meta:
    platform: linux/amd64
    image: saferwall/gometa:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/meta-svc, -config, /saferwall/conf/]
    volumes:
      - /samples:/samples

  clamav:
    platform: linux/amd64
    image: saferwall/goclamav:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/clamav-svc, -config, /saferwall/conf/]
    volumes:
      - /samples:/samples

  sandbox:
    platform: linux/amd64
    image: saferwall/sandbox:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/sandbox-svc, -config, /saferwall/conf/]
    volumes:
      - /samples:/samples

volumes:
  minio_data: null
  couchbase_data: null
