// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://about.saferwall.com/tos",
        "contact": {
            "name": "API Support",
            "url": "https://about.saferwall.com/contact.html",
            "email": "support@saferwall.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/files/": {
            "post": {
                "description": "Upload file for analysis",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file",
                    "scan"
                ],
                "summary": "Submit a new file for scanning",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.File"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/files/{sha256}": {
            "get": {
                "description": "Retrieves the content of a file report.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Get a file report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File SHA256",
                        "name": "sha256",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.File"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "patch a portion of a file report",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file",
                    "patch"
                ],
                "summary": "update a file report (partial update)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File SHA256",
                        "name": "sha256",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.File"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.File": {
            "type": "object",
            "properties": {
                "byte_entropy": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "comments_count": {
                    "type": "integer"
                },
                "crc32": {
                    "type": "string"
                },
                "exif": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "fileformat": {
                    "type": "string"
                },
                "first_seen": {
                    "type": "integer"
                },
                "histogram": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "last_scanned": {
                    "type": "integer"
                },
                "magic": {
                    "type": "string"
                },
                "md5": {
                    "type": "string"
                },
                "ml": {
                    "type": "object",
                    "additionalProperties": true
                },
                "multiav": {
                    "type": "object",
                    "additionalProperties": true
                },
                "packer": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pe": {},
                "sha1": {
                    "type": "string"
                },
                "sha256": {
                    "type": "string"
                },
                "sha512": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "ssdeep": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "strings": {},
                "submissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Submission"
                    }
                },
                "tags": {
                    "type": "object",
                    "additionalProperties": true
                },
                "trid": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "entity.Submission": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "src": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "errors.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.saferwall.com",
	BasePath:         "/v1",
	Schemes:          []string{"https"},
	Title:            "Saferwall Web API",
	Description:      "Interact with Saferwall Malware Analysis Platform",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
